environment:
  nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run test:unit

cache:
  - node_modules -> package-lock.json

build: off

branches:
  only:
    - feature/appveyor-ci